#!/bin/bash
#
# Copyright 2019 Gauthier Voron
#
# This file is part of Synctl
#
# Synctl is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Fundation, either version 3 of the License, or (at your option) any later
# version.
#
# Synctl is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANDABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Synctl. If not, see <https://www.gnu.org/licenses/>.
#


set -e
set -x

mkdir 'pushed' 'pulled' 'profile-0' 'profile-1' 'profile-2'

mktree -p 'pushed' <<EOF
root 04**** * *
root/a 040755 19990101 19990102
EOF

cat > 'profile-0/conf' <<EOF
root   = pushed/root
server = file://server
trunk  = t0
EOF

cat > 'profile-1/conf' <<EOF
root   = pushed/root
server = file://server
trunk  = t1
EOF

cat > 'profile-2/conf' <<EOF
root   = pushed/root
server = file://server
trunk  = t2
EOF


synctl init 'server'

if [ "x$(whoami)" = 'xroot' ] ; then
    rm 'profile-0/conf'
else
    chmod 000 'profile-0/conf'
fi


SYNCTL_PROFILE_PATH='null:profile-0:profile-1:profile-2' synctl push 'conf'

! synctl pull --server='file://server' --root='pulled/root' --trunk='t0'
  synctl pull --server='file://server' --root='pulled/root' --trunk='t1'
! synctl pull --server='file://server' --root='pulled/root' --trunk='t2'

chktree -p 'pulled' <<EOF
root 04**** * *
root/a 040755 19990101 19990102
EOF
