#!/bin/bash
#
# Copyright 2019 Gauthier Voron
#
# This file is part of Synctl
#
# Synctl is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Fundation, either version 3 of the License, or (at your option) any later
# version.
#
# Synctl is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANDABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Synctl. If not, see <https://www.gnu.org/licenses/>.
#


set -e
set -x

mkdir 'pushed' 'pulled' 'profiles'

mktree -p 'pushed' <<EOF
root 04**** * *
root/a 040755 19990101 19990102
root/a/b 0100644 19990103 19990104 < b\n
root/a/c 0100644 19990105 19990106 < c\n
EOF

cat > 'profiles/conf' <<EOF
trunk = t0
branch = b0
root = pushed/root
server = file://server
include = /a/b
exclude = /a/*
EOF

synctl init 'server'

synctl -C 'profiles' push 'conf'

synctl pull --server='file://server' --root='pulled/root' --trunk='t0'

chktree -p 'pulled' <<EOF
root 04**** * *
root/a 040755 19990101 19990102
root/a/b 0100644 19990103 19990104 < b\n
EOF
