#!/bin/bash
#
# Copyright 2019 Gauthier Voron
#
# This file is part of Synctl
#
# Synctl is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Fundation, either version 3 of the License, or (at your option) any later
# version.
#
# Synctl is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANDABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Synctl. If not, see <https://www.gnu.org/licenses/>.
#


set -e
set -x

if [ "x$(whoami)" != 'xroot' ] ; then
    skip 'need root privilege'
fi

cat > 'spec.txt' <<EOF
root 04**** * *
root/foo 040700 19990103 19990104 o:nobody
root/foo/f0 0100600 19990105 19990106 o:root
root/foo/l0 0120777 19990107 19990108 o:2000 = ../l0
root/l0 0120777 19990109 19990110 = foo/l0
EOF

mkdir 'pushed' 'pulled'

mktree -p 'pushed' < 'spec.txt'

synctl init 'server'
synctl push --server='file://server' --root='pushed/root'
synctl pull --server='file://server' --root='pulled/root'

chktree -p 'pulled' < 'spec.txt'
