#!/bin/bash

set -e
set -x

cat > 'spec.txt' <<EOF
root 04**** * *
root/f0-0 0100600 19990105 19990106 < content\n
root/f0-1 0100600 19990105 19990106 = root/f0-0
root/f0-2 0100600 19990105 19990106 = root/f0-0
root/f1-0 0100600 19990105 19990106 < content\n
root/f1-1 0100600 19990105 19990106 = root/f1-0
EOF

mkdir 'pushed' 'pulled'

mktree -p 'pushed' < 'spec.txt'

synctl init 'server'
synctl push --server='file://server' --root='pushed/root'
synctl pull --server='file://server' --root='pulled/root'

chktree -p 'pulled' < 'spec.txt'
