#!/bin/bash

set -e
set -x

cat > 'spec.txt' <<EOF
root 012**** * * = /usr/bin
EOF

mkdir 'pushed' 'pulled'

mktree -p 'pushed' < 'spec.txt'

synctl init 'server'
synctl push --server='file://server' --root='pushed/root'
synctl pull --server='file://server' --root='pulled/root'

chktree -p 'pulled' < 'spec.txt'
