#!/bin/bash

set -e
set -x

mkdir 'pushed' 'pulled'

mktree -p 'pushed' <<EOF
root 04**** * *
root/a 040755 19990101 19990101
root/a/x 0100644 19990101 19990101 < x\n
root/x 0100644 19990101 19990101 < x\n
EOF

synctl init 'server'

synctl push --server='file://server' --root='pushed/root' \
            --exclude='x'

synctl pull --server='file://server' --root='pulled/root'

chktree -p 'pulled' <<EOF
root 04**** * *
root/a 040755 19990101 19990101
EOF
