#!/bin/bash
#
# Copyright 2019 Gauthier Voron
#
# This file is part of Synctl
#
# Synctl is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Fundation, either version 3 of the License, or (at your option) any later
# version.
#
# Synctl is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANDABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Synctl. If not, see <https://www.gnu.org/licenses/>.
#


set -e
set -x

eval $(cmdalias 'man' <<'EOF'
#!/bin/bash
echo "$@" >> args.txt
EOF
)

cat > 'expected.txt' <<EOF
5 synctl-profile
EOF

synctl help --profile
diff 'args.txt' 'expected.txt'
rm 'args.txt'

for topic in 'tutorial' 'regex' ; do
    cat > 'expected.txt' <<EOF
7 synctl-$topic
EOF

    synctl help --$topic
    diff 'args.txt' 'expected.txt'
    rm 'args.txt'
done
