#!/bin/bash

set -e
set -x

mktree -p 'pushed' <<EOF
root 010**** * * < foo\n
EOF

synctl init 'server'

synctl push --server='file://server' --root='pushed/root' \
            --trunk='trunk-0' --branch='b0'

synctl push --server='file://server' --root='pushed/root' \
            --trunk='trunk-1' --branch='b1'

synctl push --server='file://server' --root='pushed/root' \
            --trunk='trunk-1' --branch='b1'

synctl push --server='file://server' --root='pushed/root' \
            --trunk='trunk-1' --branch='b2'

synctl list --server='file://server' --format='porcelain' \
            --trunk='trunk-1' --branch='b*' | (
    read line
    echo "$line" | grep -P '^trunk-1:[^:]+:\d{4}(-\d\d){5}-\d{9}:b2$'

    read line
    echo "$line" | grep -P '^trunk-1:[^:]+:\d{4}(-\d\d){5}-\d{9}:b1$'

    ! read line
)

synctl list --server='file://server' --format='porcelain' \
            --trunk='trunk-0' --branch='b[01]' | (
    read line
    echo "$line" | grep -P '^trunk-0:[^:]+:\d{4}(-\d\d){5}-\d{9}:b0$'

    ! read line
)

synctl list --server='file://server' --format='porcelain' \
            --trunk='trunk-1' --branch='b0' | (
    ! read line
)
