#!/bin/bash
#
# Copyright 2019 Gauthier Voron
#
# This file is part of Synctl
#
# Synctl is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Fundation, either version 3 of the License, or (at your option) any later
# version.
#
# Synctl is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANDABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Synctl. If not, see <https://www.gnu.org/licenses/>.
#


set -e
set -x

mktree -p 'pushed' <<EOF
root 010**** * * < foo\n
EOF

synctl init 'server'

synctl push --server='file://server' --root='pushed/root' \
            --trunk='trunk-0' --branch='b0'

synctl push --server='file://server' --root='pushed/root' \
            --trunk='trunk-1' --branch='b1'

synctl push --server='file://server' --root='pushed/root' \
            --trunk='trunk-1' --branch='b1'

synctl push --server='file://server' --root='pushed/root' \
            --trunk='trunk-1' --branch='b2'

synctl list --server='file://server' --format='porcelain' --branch='b1' | (
    read line
    echo "$line" | grep -P '^trunk-1:[^:]+:\d{4}(-\d\d){5}-\d{9}:b1$'

    ! read line
)

synctl list --server='file://server' --format='porcelain' --branch='b2' | (
    read line
    echo "$line" | grep -P '^trunk-1:[^:]+:\d{4}(-\d\d){5}-\d{9}:b2$'

    ! read line
)

synctl list --server='file://server' --format='porcelain' --branch='b7' | (
    ! read line
)

synctl list --server='file://server' --format='porcelain' --branch='' | (
    ! read line
)
