#!/bin/bash

set -e
set -x

cat > 'spec-0.txt' <<EOF
root 04**** * *
root/f0 0100644 19990101 19990102 < f0\n
EOF

cat > 'spec-1.txt' <<EOF
root 04**** * *
root/f0 0100644 19990103 19990104 < f0+\n
root/f1 0100644 19990105 19990106 < f1\n
EOF

mkdir 'pushed-0' 'pushed-1' 'pulled'

mktree -p 'pushed-0' < 'spec-0.txt'
mktree -p 'pushed-1' < 'spec-1.txt'

synctl init 'server'

synctl push --server='file://server' --root='pushed-0/root' --trunk='t0' \
       --branch='b0' --exclude='/f1'

synctl push --server='file://server' --root='pushed-1/root' --trunk='t0' \
       --branch='b1'

synctl pull --server='file://server' --root='pulled/root' --trunk='t0'

chktree -p 'pulled' <<EOF
root 04**** * *
root/f0 0100644 19990103 19990104 < f0+\n
root/f1 0100644 19990105 19990106 < f1\n
EOF
