#!/bin/bash
#
# Copyright 2019 Gauthier Voron
#
# This file is part of Synctl
#
# Synctl is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Fundation, either version 3 of the License, or (at your option) any later
# version.
#
# Synctl is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANDABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Synctl. If not, see <https://www.gnu.org/licenses/>.
#


set -e
set -x

cat > 'spec-0.txt' <<EOF
root 04**** * *
root/f0 0100644 19990101 19990102 < f0\n
root/f1 0100644 19990101 19990102 = root/f0
root/f2 0100644 19990101 19990102 = root/f0
EOF

cat > 'spec-1.txt' <<EOF
root 04**** * *
root/f0 0100644 19990101 19990102 < f0\n
root/f1 0100644 19990101 19990102 = root/f0
EOF

mkdir 'pushed-0' 'pushed-1' 'pulled'

mktree -p 'pushed-0' < 'spec-0.txt'
mktree -p 'pushed-1' < 'spec-1.txt'

synctl init 'server'

synctl push --server='file://server' --root='pushed-0/root' --trunk='t0' \
       --branch='b0'

synctl push --server='file://server' --root='pushed-1/root' --trunk='t0' \
       --branch='b1' --exclude='f2'

synctl pull --server='file://server' --root='pulled/root' --trunk='t0'

chktree -p 'pulled' < 'spec-0.txt'
