#!/bin/bash
#
# Copyright 2019 Gauthier Voron
#
# This file is part of Synctl
#
# Synctl is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Fundation, either version 3 of the License, or (at your option) any later
# version.
#
# Synctl is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANDABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Synctl. If not, see <https://www.gnu.org/licenses/>.
#


set -e
set -x

mkdir 'pushed-v0' 'pushed-v1' 'pulled'

mktree -p 'pushed-v0' <<EOF
root 010**** * * < v0\n
EOF

mktree -p 'pushed-v1' <<EOF
root 010**** * * < v1\n
EOF

synctl init 'server'
synctl push --server='file://server' --root='pushed-v0/root'
synctl push --server='file://server' --root='pushed-v1/root'

synctl list --server='file://server' --format='porcelain' | \
    tail -n1

v0=$(synctl list --server='file://server' --format='porcelain' | \
	 tail -n 1 | cut -d':' -f2)

synctl pull --server='file://server' --root='pulled/root' --snapshot="$v0"

chktree -p 'pulled' <<EOF
root 010**** * * < v0\n
EOF
