#!/bin/bash

set -e
set -x

mkdir 'pushed' 'pulled'

mktree -p 'pushed' <<EOF
root 04**** * *
root/a 040755 19990101 19990101
root/a/c 0100644 19990101 19990101 < a/c\n
root/b 040755 19990101 19990101
root/b/c 0100644 19990101 19990101 < a/c\n
EOF

synctl init 'server'

synctl push --server='file://server' --root='pushed/root'

synctl pull --server='file://server' --root='pulled/root' \
            --include='**/c' --include='/a' --exclude='/*'

chktree -p 'pulled' <<EOF
root 04**** * *
root/a 040755 19990101 19990101
root/a/c 0100644 19990101 19990101 < a/c\n
EOF
