#!/bin/bash
#
# Copyright 2019 Gauthier Voron
#
# This file is part of Synctl
#
# Synctl is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Fundation, either version 3 of the License, or (at your option) any later
# version.
#
# Synctl is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANDABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Synctl. If not, see <https://www.gnu.org/licenses/>.
#


set -e
set -x

mktree <<EOF
root 04**** * *
root/aaa 0100644 19990101 19990101 < a\n
EOF

synctl init 'server'
synctl push --server='file://server' --root='root'

eval $(cmdalias 'ssh' <<'EOF'
#!/bin/bash

for arg in "$@" ; do
    echo "$arg"
done > ssh-cmdline.txt

synctl server server
EOF
)

synctl pull --server='ssh://user@server:2022/~home/path' --root='root'

cat > 'expected-cmdline.txt' <<EOF
-p
2022
user@server
synctl
server
~home/path
EOF

diff 'ssh-cmdline.txt' 'expected-cmdline.txt'
