#!/bin/bash
#
# Copyright 2019 Gauthier Voron
#
# This file is part of Synctl
#
# Synctl is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Fundation, either version 3 of the License, or (at your option) any later
# version.
#
# Synctl is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANDABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Synctl. If not, see <https://www.gnu.org/licenses/>.
#


set -e
set -x

mkdir 'pushed' 'pulled'

mktree -p 'pushed' <<EOF
root 04**** * *
root/a 040755 19990101 19990101
root/a/c 0100644 19990101 19990101 < a/c\n
root/b 040755 19990101 19990101
root/b/c 0100644 19990101 19990101 < a/c\n
EOF

synctl init 'server'

synctl push --server='file://server' --root='pushed/root' \
            --include='**/c' --include='/a' --exclude='/*'

synctl pull --server='file://server' --root='pulled/root'

chktree -p 'pulled' <<EOF
root 04**** * *
root/a 040755 19990101 19990101
root/a/c 0100644 19990101 19990101 < a/c\n
EOF
