#!/bin/bash
#
# Copyright 2019 Gauthier Voron
#
# This file is part of Synctl
#
# Synctl is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Fundation, either version 3 of the License, or (at your option) any later
# version.
#
# Synctl is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANDABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Synctl. If not, see <https://www.gnu.org/licenses/>.
#


set -e
set -x

synctl init 'server'

mktree <<EOF
root 04**** * *
root/foo 0100644 19990101 19990101
EOF

synctl push --server='file://server' --root='root' --verbose > 'log-0.txt'
synctl push --server='file://server' --root='root' --verbose > 'log-1.txt'

rm -rf 'root'
mktree <<EOF
root 04**** * *
root/foo 0100644 19990101 19990101
root/bar 0100644 19990102 19990102
EOF

synctl push --server='file://server' --root='root' --verbose > 'log-2.txt'

cat 'log-0.txt' | perl -wple 's/^.*\r//g' | {
    read line
    echo "$line" | \
	grep -qP '^Sent files: 2/2, \d+ ([GMK]i)?B | \d+ ([GMK]i)?B/s$'

    read line
    echo "$line" | \
	grep -qP '^Created snapshot: master/\S+ <- '

    echo ok
    ! read line
}

cat 'log-1.txt' | perl -wple 's/^.*\r//g' | {
    read line
    echo "$line" | \
	grep -P '^Received references: 2, \d+ ([GMK]i)?B | \d+ ([GMK]i)?B/s$'

    read line
    echo "$line" | \
	grep -P '^Created snapshot: master/\S+ <- '

    ! read line
}

cat 'log-2.txt' | perl -wple 's/^.*\r//g' | {
    read line
    echo "$line" | \
	grep -P '^Received references: 2, \d+ ([GMK]i)?B | \d+ ([GMK]i)?B/s$'

    read line
    echo "$line" | \
	grep -P '^Sent files: 1/3, \d+ ([GMK]i)?B | \d+ ([GMK]i)?B/s$'

    read line
    echo "$line" | \
	grep -P '^Created snapshot: master/\S+ <- '

    ! read line
}
