#!/bin/bash
#
# Copyright 2019 Gauthier Voron
#
# This file is part of Synctl
#
# Synctl is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Fundation, either version 3 of the License, or (at your option) any later
# version.
#
# Synctl is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANDABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Synctl. If not, see <https://www.gnu.org/licenses/>.
#


set -e
set -x

cat > 'spec.txt' <<EOF
root 04**** * *
root/aaa 0100644 19990101 19990101 < a\n
EOF

eval $(cmdalias 'ssh' <<'EOF'
#!/bin/bash

for arg in "$@" ; do
    path="$arg"
done

synctl server "$path"
EOF
)

mkdir 'pushed' 'pulled'

mktree -p 'pushed' < 'spec.txt'

synctl init 'server'

path="$PWD/server"
rpath="${path#$HOME/}"
if [ "x$rpath" = "x$path" ] ; then
    rpath="$(echo "$HOME" | sed -r 's/[^/]+/../g')$path"
fi

synctl push --server="ssh://localhost/~$USER/$rpath" --root='pushed/root'

synctl pull --server='file://server' --root='pulled/root'

chktree -p 'pulled' < 'spec.txt'
