#!/bin/bash
#
# Copyright 2019 Gauthier Voron
#
# This file is part of Synctl
#
# Synctl is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Fundation, either version 3 of the License, or (at your option) any later
# version.
#
# Synctl is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANDABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Synctl. If not, see <https://www.gnu.org/licenses/>.
#

#
#   measure - measure the time a command takes to execute
#
#   Usage: measure <title> <command> <args...>     (1)
#          measure <header>                        (2)
#
#   (1) Execute the given command with the provided arguments and measure its
#       execution time. Report this time along with the specified title at
#       csv format on stderr or in $MEASURE_OUTPUT if this environment variable
#       is not empty.
#
#   (2) Print the specified header on stderr or in $MEASURE_OUTPUT if this
#       environment variable is not empty.
#

if [ "x${MEASURE_OUTPUT}" != 'x' ] ; then
    printf '%s' "$1" >> "${MEASURE_OUTPUT}" ; shift

    if [ $# -eq 0 ] ; then
	printf '\n' >> "${MEASURE_OUTPUT}"
	exit 0
    else
	printf ',' >> "${MEASURE_OUTPUT}"
    fi

    /usr/bin/time --format='%e' --output="${MEASURE_OUTPUT}" --append "$@"
else
    printf '%s' "$1" >&2 ; shift

    if [ $# -eq 0 ] ; then
	printf '\n' >&2
	exit 0
    else
	printf ',' >&2
    fi

    /usr/bin/time --format='%e' "$@"
fi
