#!/bin/bash
#
# Copyright 2019 Gauthier Voron
#
# This file is part of Synctl
#
# Synctl is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Fundation, either version 3 of the License, or (at your option) any later
# version.
#
# Synctl is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANDABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Synctl. If not, see <https://www.gnu.org/licenses/>.
#

#
#   mkflat - generate random files
#
#   Generate a given number of files with a given name pattern and fill them
#   with a specified number of random bytes.
#


num=$1 ; shift
pattern="$1" ; shift
size=$1 ; shift

ncpu=$(grep 'processor' '/proc/cpuinfo' | wc -l)
chunk=$(( num / ncpu ))
did=0
num=$(( num - 1 ))

for i in $(seq 1 $ncpu) ; do
    (
	for j in $(seq $did $(( did + chunk - 1 ))) ; do
	    file=$(printf "$pattern" $j)
	    dd if='/dev/urandom' of="$file" count=1 bs=$size \
	       > /dev/null 2> /dev/null
	done
    ) &
    did=$(( did + chunk ))
done

if [ $did -le $num ] ; then
    for j in $(seq $did $num) ; do
	file=$(printf "$pattern" $j)
	dd if='/dev/urandom' of="$file" count=1 bs=$size \
	   > /dev/null 2> /dev/null
    done
fi

wait
