#!/bin/bash
#
# Copyright 2019 Gauthier Voron
#
# This file is part of Synctl
#
# Synctl is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Fundation, either version 3 of the License, or (at your option) any later
# version.
#
# Synctl is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANDABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Synctl. If not, see <https://www.gnu.org/licenses/>.
#

#
#   skip - skip a test or benchmark case, possibly explaining the reason
#
#   Usage: skip [<reason>]
#
#   Exit the case immediately, informing the case execution script that this
#   case is skipped.
#   If <reason> is specified, also indicate why the case has been skipped.
#

if [ "x${SKIP_FILE}" != 'x' ] ; then
    echo "$1" > "${SKIP_FILE}"
else
    echo "cannot skip properly: 'SKIP_FILE' is not defined" >&2
fi

exit 1
